#!/bin/sh

# This file should be placed in /etc/profile, for OpenWRT

[ -f /etc/banner ] && cat /etc/banner

export PATH=/bin:/sbin:/usr/bin:/usr/sbin
export HOME=$(grep -e "^${USER:-root}:" /etc/passwd | cut -d ":" -f 6)
export HOME=${HOME:-/root}
export PS1='\u@\h:\w\$ '

[ -x /bin/more ] || alias more=less
[ -x /usr/bin/vim ] && alias vi=vim || alias vim=vi

[ -z "$KSH_VERSION" -o \! -s /etc/mkshrc ] || . /etc/mkshrc

[ -x /usr/bin/arp ] || arp() { cat /proc/net/arp; }
[ -x /usr/bin/ldd ] || ldd() { LD_TRACE_LOADED_OBJECTS=1 $*; }

# Custom aliases
alias ls='ls --color=always'
alias ll='ls -lh'
alias la='ls -alh'
alias l='ls -ahl'
alias lt='ls -ahltr'

# Custom PS1
PS1='\[\033[35;1m\]\u\[\033[0m\]@\[\033[31;1m\]\h:\[\033[32;1m\]$PWD\[\033[0m\]\[\033[31m\]\$\[\033[0m\] '
PS1='\[\033[0;31m\]\u\[\033[0;32m\]@\[\033[0;32m\]\h\[\033[0m\]:\w# \e[0m'

# OPKG coloration
opkg () {
        BOLD=$(echo -e '\033[35;1m');
        NORM=$(echo -e '\033[0m');
        COL="no";
        for arg in $*; do
                if [ $arg == "whatdepends" -o $arg == "list" \
                -o $arg == "list-installed" -o $arg == "list-upgradable" \
                -o $arg == "list-changed-conffiles" -o $arg == "status" \
                -o $arg == "info" -o $arg == "find" ]; then
                        COL="yes";
                        break;
                fi
        done
        if [ $COL == "yes" ]; then
                # (|\t*) added for 'whatdepends'
                /bin/opkg $* | sed -re "s/^(|\t*)[a-z0-9-]*/$BOLD&$NORM/g";
        else
                /bin/opkg $*;
        fi
}
